project_id = "evaajkvqaysfqjlmathl"

[functions.send-welcome-email]
verify_jwt = false

[functions.send-plan-receipt]
verify_jwt = false

[functions.firebase-data]
verify_jwt = false

[functions.predict-salary]
verify_jwt = false

[functions.send-limit-reached]
verify_jwt = false

[functions.send-expiring-plan-reminder]
verify_jwt = false

