import { motion } from "framer-motion";
import { Heart, Sparkles, Target, Users, Coffee } from "lucide-react";
import SEOHead from "@/components/SEOHead";
import AdsterraResponsiveBanner from "@/components/AdsterraResponsiveBanner";

export default function Story() {
  return (
    <div className="min-h-screen py-16 bg-background">
      <SEOHead
        title="Our Story — SkillTa"
        description="The story behind SkillTa — why we're building a free, ad-free AI career guidance platform for students."
      />
      <AdsterraResponsiveBanner />
      <div className="container mx-auto px-6 max-w-3xl">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center mb-12"
        >
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-primary/15 border border-primary/30 mb-5">
            <Heart className="w-7 h-7 text-primary" />
          </div>
          <h1 className="text-4xl md:text-5xl font-bold mb-4">
            The <span className="text-gradient">SkillTa</span> Story
          </h1>
          <p className="text-muted-foreground text-lg">
            Why we built a free AI career platform — and why we need your help to keep it that way.
          </p>
        </motion.div>

        <div className="space-y-8 text-foreground/90 leading-relaxed">
          <section className="p-6 rounded-2xl bg-gradient-card border border-border">
            <div className="flex items-center gap-3 mb-3">
              <Sparkles className="w-5 h-5 text-primary" />
              <h2 className="text-xl font-bold">Where it started</h2>
            </div>
            <p>
              SkillTa started with a simple frustration: thousands of students in India and around the
              world spend years choosing a tech career based on YouTube hype, random Reddit threads, or
              whatever their friends picked. There was no honest, personalized guide — just noise,
              coaching ads, and "top 10 careers" listicles. We wanted to build the tool we wished we had
              when we were 17: an AI that actually listens, understands your strengths, and gives you a
              real roadmap — not a sales pitch.
            </p>
          </section>

          <section className="p-6 rounded-2xl bg-gradient-card border border-border">
            <div className="flex items-center gap-3 mb-3">
              <Target className="w-5 h-5 text-primary" />
              <h2 className="text-xl font-bold">Our mission</h2>
            </div>
            <p>
              SkillTa exists to make career guidance <strong>free, honest, and ad-free</strong> for every
              student. No paywalls hiding the real advice. No "premium consultants" upselling you. No
              creepy ads following you across the internet. Just a 10-question AI quiz, a personalized
              roadmap, and a library of 50+ tech career paths — all free, forever if we can help it.
            </p>
          </section>

          <section className="p-6 rounded-2xl bg-gradient-card border border-border">
            <div className="flex items-center gap-3 mb-3">
              <Users className="w-5 h-5 text-primary" />
              <h2 className="text-xl font-bold">The hard truth about running SkillTa</h2>
            </div>
            <p className="mb-3">
              Building SkillTa costs real money every single day. Here's where it goes:
            </p>
            <ul className="space-y-2 text-sm text-muted-foreground list-disc pl-5">
              <li><strong className="text-foreground">AI API bills</strong> — every quiz result you get is generated by an AI model that charges us per request.</li>
              <li><strong className="text-foreground">Domain & hosting</strong> — skillta.tech, server bills, database, and email delivery are ongoing costs.</li>
              <li><strong className="text-foreground">Marketing</strong> — reaching students who need this the most costs money we don't have yet.</li>
              <li><strong className="text-foreground">Development time</strong> — hours of coding, designing, and testing every feature.</li>
            </ul>
          </section>

          <section className="p-6 rounded-2xl border border-yellow-400/30 bg-yellow-400/5">
            <div className="flex items-center gap-3 mb-3">
              <Coffee className="w-5 h-5 text-yellow-400" />
              <h2 className="text-xl font-bold">Why we're asking for your help</h2>
            </div>
            <p className="mb-3">
              We have a choice to make. If we can't cover these costs through small donations from
              students who found SkillTa useful, we will be <strong>forced to integrate ads</strong> —
              banner ads, popup ads, sponsored career recommendations. We don't want that. You don't
              want that. Ads would ruin the honest, clean experience we've built.
            </p>
            <p>
              A single ₹250 (~$3) donation on Ko-fi covers roughly a full day of AI costs for one
              student's complete career analysis. If even 1 out of every 100 students who use SkillTa
              donates once, we can stay 100% free and 100% ad-free — forever.
            </p>
          </section>

          <section className="p-6 rounded-2xl bg-gradient-card border border-border">
            <h2 className="text-xl font-bold mb-3">What your donation unlocks (for everyone)</h2>
            <ul className="space-y-2 text-sm text-muted-foreground list-disc pl-5">
              <li>No ads. Ever.</li>
              <li>Better AI models for more accurate career matches.</li>
              <li>More career roadmaps, blog guides, and comparison tools.</li>
              <li>Free access for students who genuinely can't afford paid platforms.</li>
              <li>A small indie project that stays independent — not owned by an ed-tech giant.</li>
            </ul>
          </section>

          <section className="text-center py-4">
            <p className="text-muted-foreground text-sm mb-6">
              If SkillTa helped you find your path, please consider chipping in. Every donation, no
              matter how small, helps us stay free for the next student.
            </p>
            <a
              href="https://ko-fi.com/A0A620ZLB9"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 bg-yellow-400 text-gray-900 px-8 py-4 rounded-full text-base font-bold hover:scale-105 transition-transform shadow-lg"
            >
              ☕ Keep SkillTa Free · Donate on Ko-fi
            </a>
            <p className="text-xs text-muted-foreground mt-4">
              Thank you for being part of the SkillTa story. 💜
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
